package cc.nfscan.server.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

/**
 * Entity class that represents Electronic TaxReceipt (CF-e and SAT) on database
 *
 * @author Paulo Miguel Almeida <a href="http://github.com/PauloMigAlmeida">@PauloMigAlmeida</a>
 */
@DynamoDBTable(tableName = "NFSCAN-ELECTRONICTAXRECEIPT")
public class ElectronicTaxReceipt implements IDomain {

    private static final long serialVersionUID = 1L;

    /**
     * identifier
     */
    private String id;

    /**
     * access key that contains all required receipt information to donate
     */
    private String accessKey;

    /**
     * total
     */
    private Double total;

    /**
     * dateInsertion of this object
     */
    private Date dateInsertion;


    public ElectronicTaxReceipt(String accessKey, double total) {
        this.accessKey = accessKey;
        this.total = total;
        this.dateInsertion = new Date();
    }

    @DynamoDBAutoGeneratedKey()
    @DynamoDBHashKey(attributeName = "electronictaxreceipt_id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "accessKey")
    public String getAccessKey() {
        return accessKey;
    }

    public void setAccessKey(String accessKey) {
        this.accessKey = accessKey;
    }

    @DynamoDBAttribute(attributeName = "total")
    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    @DynamoDBAttribute(attributeName = "dateInsertion")
    public Date getDateInsertion() {
        return dateInsertion;
    }

    public void setDateInsertion(Date dateInsertion) {
        this.dateInsertion = dateInsertion;
    }

    @Override
    public String toString() {
        return "ElectronicTaxReceipt{" +
                "id='" + id + '\'' +
                ", accessKey='" + accessKey + '\'' +
                ", total=" + total +
                ", dateInsertion=" + dateInsertion +
                '}';
    }
}